begin;
insert into public.ingredient (name, department, pantry_default) values
($m$aleppo pepper$m$,$m$Seasoning$m$,false),
($m$all-purpose flour$m$,$m$Pantry$m$,false),
($m$anchovy fillet$m$,$m$Pantry$m$,false),
($m$anchovy paste$m$,$m$Pantry$m$,false),
($m$apricot jam$m$,$m$Pantry$m$,false),
($m$arugula$m$,$m$Produce$m$,false),
($m$asparagus$m$,$m$Produce$m$,false),
($m$baby potato$m$,$m$Produce$m$,false),
($m$baby spinach$m$,$m$Produce$m$,false),
($m$bacon$m$,$m$Protein$m$,false),
($m$baguette$m$,$m$Bread$m$,false),
($m$baharat$m$,$m$Seasoning$m$,false),
($m$baking powder$m$,$m$Pantry$m$,false),
($m$bay leaf$m$,$m$Seasoning$m$,false),
($m$beef stock$m$,$m$Pantry$m$,false),
($m$bird's eye chilli$m$,$m$Produce$m$,false),
($m$black pepper$m$,$m$Seasoning$m$,false),
($m$black peppercorn$m$,$m$Seasoning$m$,false),
($m$brandy / cognac$m$,$m$Oils & Liquids$m$,true),
($m$brisket fat$m$,$m$Oils & Liquids$m$,false),
($m$brisket jus$m$,$m$Pantry$m$,false),
($m$broccolini$m$,$m$Produce$m$,false),
($m$brown onion$m$,$m$Produce$m$,false),
($m$butter$m$,$m$Dairy$m$,false),
($m$butter lettuce / baby cos$m$,$m$Produce$m$,false),
($m$buttermilk$m$,$m$Dairy$m$,false),
($m$cabbage$m$,$m$Produce$m$,false),
($m$cannellini beans, tinned$m$,$m$Pantry$m$,false),
($m$capers in brine$m$,$m$Pantry$m$,false),
($m$carrot$m$,$m$Produce$m$,false),
($m$caster sugar$m$,$m$Pantry$m$,false),
($m$cayenne$m$,$m$Seasoning$m$,false),
($m$celery rib$m$,$m$Produce$m$,false),
($m$celery stalk$m$,$m$Produce$m$,false),
($m$cherry tomato$m$,$m$Produce$m$,false),
($m$chicken broth$m$,$m$Oils & Liquids$m$,false),
($m$chicken stock$m$,$m$Pantry$m$,false),
($m$chicken stock, low-sodium$m$,$m$Pantry$m$,false),
($m$chicken thigh, bone-in$m$,$m$Protein$m$,false),
($m$chicken thigh, bone-in, skin-on$m$,$m$Protein$m$,false),
($m$chicken thigh, boneless skinless$m$,$m$Protein$m$,false),
($m$chicken wing$m$,$m$Protein$m$,false),
($m$chili flake$m$,$m$Seasoning$m$,false),
($m$chilli flake$m$,$m$Seasoning$m$,false),
($m$chilli flakes$m$,$m$Seasoning$m$,false),
($m$cilantro, fresh$m$,$m$Produce$m$,false),
($m$corn$m$,$m$Produce$m$,false),
($m$cornstarch$m$,$m$Pantry$m$,false),
($m$couscous$m$,$m$Pantry$m$,false),
($m$crushed tomatoes, tinned$m$,$m$Pantry$m$,false),
($m$crème fraîche$m$,$m$Dairy$m$,false),
($m$cucumber$m$,$m$Produce$m$,false),
($m$cucumber, japanese or persian$m$,$m$Produce$m$,false),
($m$dark-fruit jam$m$,$m$Pantry$m$,false),
($m$diamond crystal kosher salt$m$,$m$Seasoning$m$,false),
($m$dijon mustard$m$,$m$Pantry$m$,false),
($m$dill$m$,$m$Produce$m$,false),
($m$dill, fresh$m$,$m$Produce$m$,false),
($m$dried greek oregano$m$,$m$Seasoning$m$,false),
($m$dried oregano$m$,$m$Seasoning$m$,false),
($m$dried thyme$m$,$m$Seasoning$m$,false),
($m$dry red wine$m$,$m$Alcohol$m$,false),
($m$dry white wine$m$,$m$Alcohol$m$,false),
($m$dry white wine (sauvignon blanc)$m$,$m$Alcohol$m$,false),
($m$egg$m$,$m$Dairy$m$,false),
($m$egg yolk$m$,$m$Dairy$m$,false),
($m$endive$m$,$m$Produce$m$,false),
($m$english cucumber$m$,$m$Produce$m$,false),
($m$extra virgin olive oil$m$,$m$Oils & Liquids$m$,false),
($m$extra-virgin olive oil$m$,$m$Oils & Liquids$m$,false),
($m$extra-virgin olive oil, mild$m$,$m$Oils & Liquids$m$,false),
($m$fennel bulb$m$,$m$Produce$m$,false),
($m$fennel seed$m$,$m$Seasoning$m$,false),
($m$feta$m$,$m$Dairy$m$,false),
($m$fine salt$m$,$m$Seasoning$m$,false),
($m$fine sea salt$m$,$m$Seasoning$m$,false),
($m$fine white sugar$m$,$m$Pantry$m$,false),
($m$flaky salt$m$,$m$Seasoning$m$,false),
($m$flaky sea salt$m$,$m$Seasoning$m$,false),
($m$flat-leaf parsley$m$,$m$Produce$m$,false),
($m$flour$m$,$m$Pantry$m$,false),
($m$fresh dill$m$,$m$Produce$m$,false),
($m$fresh lemon juice$m$,$m$Produce$m$,false),
($m$fresh parsley$m$,$m$Produce$m$,false),
($m$frisée$m$,$m$Produce$m$,false),
($m$frozen thin fries$m$,$m$Frozen$m$,false),
($m$garlic$m$,$m$Produce$m$,false),
($m$garlic bulb$m$,$m$Produce$m$,false),
($m$garlic powder$m$,$m$Seasoning$m$,false),
($m$ginger, fresh$m$,$m$Produce$m$,false),
($m$granulated sugar$m$,$m$Pantry$m$,false),
($m$grapefruit$m$,$m$Produce$m$,false),
($m$greek yogurt$m$,$m$Dairy$m$,false),
($m$greek yogurt, full-fat$m$,$m$Dairy$m$,false),
($m$green bean$m$,$m$Produce$m$,false),
($m$green bean, frozen$m$,$m$Frozen$m$,false),
($m$ground coriander$m$,$m$Seasoning$m$,false),
($m$ground cumin$m$,$m$Seasoning$m$,false),
($m$ground nutmeg$m$,$m$Seasoning$m$,false),
($m$haricots verts$m$,$m$Produce$m$,false),
($m$heavy cream$m$,$m$Dairy$m$,false),
($m$honey$m$,$m$Pantry$m$,false),
($m$hot sauce$m$,$m$Pantry$m$,false),
($m$hot water$m$,$m$Oils & Liquids$m$,false),
($m$italian parsley$m$,$m$Produce$m$,false),
($m$japanese cucumber$m$,$m$Produce$m$,false),
($m$japanese short-grain rice$m$,$m$Pantry$m$,false),
($m$kalamata olive$m$,$m$Pantry$m$,false),
($m$kombu$m$,$m$Pantry$m$,false),
($m$kosher salt$m$,$m$Seasoning$m$,false),
($m$kosher salt, diamond crystal$m$,$m$Seasoning$m$,false),
($m$lamb roasting juices$m$,$m$Oils & Liquids$m$,false),
($m$lamb shoulder, bone-in$m$,$m$Protein$m$,false),
($m$lardon$m$,$m$Protein$m$,false),
($m$lemon$m$,$m$Produce$m$,false),
($m$lemon juice$m$,$m$Produce$m$,false),
($m$lemon juice or sesame oil$m$,$m$Oils & Liquids$m$,false),
($m$lemon juice or sherry vinegar$m$,$m$Oils & Liquids$m$,false),
($m$lemon juice, fresh$m$,$m$Produce$m$,false),
($m$lemon peel$m$,$m$Produce$m$,false),
($m$lemon wedge$m$,$m$Produce$m$,false),
($m$lemon zest$m$,$m$Produce$m$,false),
($m$light brown sugar$m$,$m$Pantry$m$,false),
($m$lime$m$,$m$Produce$m$,false),
($m$lime juice$m$,$m$Produce$m$,false),
($m$linguine or spaghetti$m$,$m$Pantry$m$,false),
($m$little gem lettuce$m$,$m$Produce$m$,false),
($m$long-grain white rice$m$,$m$Pantry$m$,false),
($m$manila clam$m$,$m$Protein$m$,false),
($m$molasses$m$,$m$Pantry$m$,false),
($m$mont-saint-michel mussel$m$,$m$Protein$m$,false),
($m$mushroom, frozen$m$,$m$Frozen$m$,false),
($m$mushroom, white or brown$m$,$m$Produce$m$,false),
($m$neutral oil$m$,$m$Oils & Liquids$m$,false),
($m$noilly prat dry vermouth$m$,$m$Alcohol$m$,false),
($m$nutmeg$m$,$m$Seasoning$m$,false),
($m$olive oil$m$,$m$Oils & Liquids$m$,false),
($m$onion$m$,$m$Produce$m$,false),
($m$onion or shallot$m$,$m$Produce$m$,false),
($m$onion powder$m$,$m$Seasoning$m$,false),
($m$orange$m$,$m$Produce$m$,false),
($m$orange juice$m$,$m$Produce$m$,false),
($m$orange zest$m$,$m$Produce$m$,false),
($m$panko breadcrumb$m$,$m$Pantry$m$,false),
($m$paprika$m$,$m$Seasoning$m$,false),
($m$parmesan$m$,$m$Dairy$m$,false),
($m$parmigiano-reggiano$m$,$m$Dairy$m$,false),
($m$parsley$m$,$m$Produce$m$,false),
($m$parsley leaves$m$,$m$Produce$m$,false),
($m$parsley stems$m$,$m$Produce$m$,false),
($m$parsley, flat-leaf$m$,$m$Produce$m$,false),
($m$pasta cooking water$m$,$m$Pantry$m$,false),
($m$peanut butter, natural unsweetened$m$,$m$Pantry$m$,false),
($m$pearl barley$m$,$m$Pantry$m$,false),
($m$pearl onion$m$,$m$Produce$m$,false),
($m$pepper$m$,$m$Seasoning$m$,false),
($m$picanha (rump cap)$m$,$m$Protein$m$,false),
($m$pineapple, ripe$m$,$m$Produce$m$,false),
($m$pita round$m$,$m$Bread$m$,false),
($m$plum$m$,$m$Produce$m$,false),
($m$polenta$m$,$m$Pantry$m$,false),
($m$pomegranate molasses$m$,$m$Pantry$m$,false),
($m$pork braising liquor, reserved$m$,$m$Oils & Liquids$m$,false),
($m$pork shoulder, boneless$m$,$m$Protein$m$,false),
($m$potato$m$,$m$Produce$m$,false),
($m$potato, yukon gold or russet$m$,$m$Produce$m$,false),
($m$powdered sugar$m$,$m$Pantry$m$,false),
($m$pumpkin purée$m$,$m$Pantry$m$,false),
($m$radish$m$,$m$Produce$m$,false),
($m$red onion$m$,$m$Produce$m$,false),
($m$red wine vinegar$m$,$m$Oils & Liquids$m$,false),
($m$red wine, pinot noir / burgundy style$m$,$m$Oils & Liquids$m$,false),
($m$rice vinegar$m$,$m$Oils & Liquids$m$,false),
($m$rice wine vinegar$m$,$m$Oils & Liquids$m$,false),
($m$roasted unsalted peanuts$m$,$m$Pantry$m$,false),
($m$sage, fresh$m$,$m$Produce$m$,false),
($m$salmon fillet$m$,$m$Protein$m$,false),
($m$salmon, centre-cut, skin-on$m$,$m$Protein$m$,false),
($m$salt$m$,$m$Seasoning$m$,false),
($m$salted butter$m$,$m$Dairy$m$,false),
($m$sesame seed$m$,$m$Pantry$m$,false),
($m$shallot$m$,$m$Produce$m$,false),
($m$sherry or red wine vinegar$m$,$m$Oils & Liquids$m$,false),
($m$sherry vinegar$m$,$m$Oils & Liquids$m$,false),
($m$shishito pepper$m$,$m$Produce$m$,false),
($m$short rib, bone-in$m$,$m$Protein$m$,false),
($m$small red potato$m$,$m$Produce$m$,false),
($m$smoked paprika$m$,$m$Seasoning$m$,false),
($m$sourdough loaf$m$,$m$Bread$m$,false),
($m$soy sauce$m$,$m$Pantry$m$,false),
($m$spaghetti$m$,$m$Pantry$m$,false),
($m$spinach, kale, or swiss chard$m$,$m$Produce$m$,false),
($m$st. louis pork ribs$m$,$m$Protein$m$,false),
($m$sugar$m$,$m$Pantry$m$,false),
($m$sumac$m$,$m$Seasoning$m$,false),
($m$sweet paprika$m$,$m$Seasoning$m$,false),
($m$sweet potato$m$,$m$Produce$m$,false),
($m$sweet tart crust$m$,$m$Bread$m$,false),
($m$tahini$m$,$m$Pantry$m$,false),
($m$thyme$m$,$m$Produce$m$,false),
($m$toasted nut$m$,$m$Pantry$m$,false),
($m$tomato$m$,$m$Produce$m$,false),
($m$tomato paste$m$,$m$Pantry$m$,true),
($m$unsalted butter$m$,$m$Dairy$m$,false),
($m$vanilla$m$,$m$Pantry$m$,false),
($m$vanilla bean$m$,$m$Pantry$m$,false),
($m$vanilla extract$m$,$m$Pantry$m$,false),
($m$vinegar$m$,$m$Oils & Liquids$m$,false),
($m$wagyu sirloin, mb5+$m$,$m$Protein$m$,false),
($m$wasabi$m$,$m$Seasoning$m$,false),
($m$water$m$,$m$Pantry$m$,false),
($m$water or light stock$m$,$m$Pantry$m$,false),
($m$white pepper$m$,$m$Seasoning$m$,false),
($m$white sandwich bread (pain de mie)$m$,$m$Bread$m$,false),
($m$whole chicken$m$,$m$Protein$m$,false),
($m$whole milk$m$,$m$Dairy$m$,false),
($m$worcestershire sauce$m$,$m$Pantry$m$,false),
($m$yellow onion$m$,$m$Produce$m$,false),
($m$yogurt$m$,$m$Dairy$m$,false),
($m$yukon gold potato$m$,$m$Produce$m$,false),
($m$yuzu kosho$m$,$m$Seasoning$m$,false),
($m$za’atar$m$,$m$Seasoning$m$,false)
on conflict (name) do nothing;
commit;
